version: '3'
services:
  nginx:
    image: mjspk/nginx:latest
    depends_on:
      - api
      - client
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3050:80"

  api:
    image: mjspk/api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    image: mjspk/client:latest
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    


