version: '3'
services:
  nginx:
    image: mjspk/bbcast_nginx:latest
    depends_on:
      - api
      - client
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8660:8660"

  api:
    image: mjspk/bbcast_api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
   

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    image: mjspk/bbcast_client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    


